### PR TITLE
Enhance gather-crds so it can also be used downstream

### PR DESCRIPTION
**Pull request by joeg-pro**
This PR enhances the `gather-crds.sh` script so it can be used downstream as well as upstream.  I've also added some error checking and other fit-and-finish to make it more robust for use in builds.

I've tested this in a ubi8/ubi and ubi8/ubi-minimal containers.  In both cases, some extra stuff has to be installed in the container to run this as noted in comments:  the git package, and if using ubi8-minimal, the findutils package.

I've NOT tested on Mac (don't have one) so I might be introducing some Mac incompatibilities since I do not naturally code Bash around the ancient Bash in Mac's limitations.

Once this is merged, I will take the next step of having downstream use this script from the hub-operator repo vs. having similar logic in downstream-specific parts.

### CODE REVIEW

**Comment by JakobGray** [comment]
Sorry Joe, I didn't get a chance to look at this today. I pull the branch and hit an error running `make update-crds`
```
make update-crds
bash cicd-scripts/gather-crds.sh https://github.com/open-cluster-management/hub-crds.git main ./crds
mktemp: illegal option -- p
usage: mktemp [-d] [-q] [-t prefix] [-u] template ...
       mktemp [-d] [-q] [-u] -t prefix 
Cloning CRD repo.
fatal: could not create work tree dir '': No such file or directory
ERROR: Could not clone upstream Hub CRDs repo.
make: *** [update-crds] Error 3
```
I'll look more into it a little later

**Comment by joeg-pro** [comment]
Ugh.  Seems like a Mac-compatibility problem.  Its not that I hate Macs, but I hate that the ancient shell-and-utilities of a Mac is constraining how we can do build stuff which is otherwise RHEL or UBI based.  If you can suggest a quick fix that works for Mac and RHEL too, I guess we can go with that.  Otherwise, I may need you to  approve anyway and we'll work out Mac problems later.  This is critical path to getting alignment between downstream and upstream CI processes that we should have as we go into Prow.

**Comment by JakobGray** [comment]
@joeg-pro You mentioned that the script would need to install some things first if run with a `ubi8/ubi-minimal` image. Could you list those prereqs here?

**Comment by joeg-pro** [comment]
I've changed the new gather-crds to use a Mac-compatible invocation of mktemp.  Also, as Jake and I discussed, I've reverted the Makefile change and have it back to using the original gather-crds script for dev use cases.  So in net, this PR now just drops in a new gather-crds into cicd-scripts.

**Pull request merged**
