### PR TITLE
Allow create & delete for managedclusterviews

### PR DESCRIPTION
**Pull request by zlayne**
Related issue: https://github.com/open-cluster-management/backlog/issues/11243

### CODE REVIEW

**Comment by jlpadilla** [comment]
/approve
/lgtm

@ckandag Can review?

**Comment by ckandag** [comment]
@zlayne @jlpadilla  : I approved but in the issue it said this used to work before, I went back and looked at the history and it dint have create/delete even in release 2.0 or 2.1. ??

Probably best if someone in server foundation team also  takes a look at this . @qiujian16 .

**Review by ckandag — APPROVED** [review]

**Review by smithbw88 — APPROVED** [review]
LGTM, thanks!

**Comment by nathanweatherly** [comment]
Is there a reason this couldn't wait until someone on installer looked at it before merging?
And did anyone pull and test this code before merging?

**Comment by smithbw88** [comment]
I did my approval because we were (supposedly) waiting on this fix to build 2.2.2 RC3, it had already been approved by one user, and nobody was taking any action.

**Pull request merged**
