### PR TITLE
Allow auth for pods/log

### PR DESCRIPTION
**Pull request by zlayne**
Related issue: https://github.com/open-cluster-management/backlog/issues/11242

FYI @jlpadilla

### CODE REVIEW

**Review by jlpadilla — APPROVED** [review]
LGTM

**Comment by zlayne** [comment]
`approved`

**Review by zlayne — COMMENTED** [review]
approved

**Review by ckandag — APPROVED** [review]

**Comment by nathanweatherly** [comment]
Is there a reason this couldn't wait until someone on installer looked at it before merging?

**Comment by nathanweatherly** [comment]
And did anyone pull and test this code before merging?

**Pull request merged**
