### PR TITLE
add argoproj.io

### PR DESCRIPTION
**Pull request by chenz4027**
Add apiGroup & resources for argocd applications

https://github.com/open-cluster-management/backlog/issues/10856

### CODE REVIEW

**Review by ckandag — APPROVED** [review]

**Comment by JakobGray** [comment]
@chenz4027 I added the `argoproj.io` apiGroup to the Installer's Role and regenerated the CSV. This is to be sure the installer has the authority to create other RBAC resources with this authority.

I guess I pushed it directly into your forked branch. I didn't know I could do that.

**Review by JakobGray — APPROVED** [review]

**Comment by chenz4027** [comment]
Thanks @JakobGray @zlayne - Yeah fork is really easy to use 👍

**Pull request merged**
